### ISSUE TITLE
TypeError: Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by aymather** [drawrowfly/tiktok-scraper#183]
I just installed the newest version of tiktok-scraper and I'm trying to make a basic request for posts by hashtag like this.

```
const TikTokScraper = require('tiktok-scraper');
test = async () => {

    try {
        const posts = await TikTokScraper.hashtag('justinbieber');
        console.log(posts);
    } catch (err) {
        console.log(err);
    }
}

test()
```

And I'm getting the following error:
```
TypeError: Cannot read property 'userAgent' of undefined
    at promiseScraper (/Users/alecmather/Desktop/Projects/vd-testing/node_modules/tiktok-scraper/build/entry.js:57:43)
    at Object.exports.hashtag (/Users/alecmather/Desktop/Projects/vd-testing/node_modules/tiktok-scraper/build/entry.js:74:45)
    at test (/Users/alecmather/Desktop/Projects/vd-testing/tiktok.js:106:43)
    at Object.<anonymous> (/Users/alecmather/Desktop/Projects/vd-testing/tiktok.js:117:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by drawrowfly** [comment]
Will be fixed with the next update. For now you can use

await TikTokScraper.hashtag('justinbieber', {randomUa: true});

**Comment by drawrowfly** [comment]
Fix in the latest update
