### ISSUE TITLE
Error: Data should not be empty or the "fields" option should be included

### ISSUE THREAD

**Issue by el-lsan** [drawrowfly/tiktok-scraper#2]
I'm getting following error:

```
Error: Data should not be empty or the "fields" option should be included
    at JSON2CSVParser.preprocessData (/Users/ehsan/.config/yarn/global/node_modules/json2csv/dist/json2csv.cjs.js:1484:15)
    at JSON2CSVParser.parse (/Users/ehsan/.config/yarn/global/node_modules/json2csv/dist/json2csv.cjs.js:1450:32)
    at Bluebird.fromCallback.cb (/Users/ehsan/.config/yarn/global/node_modules/tiktok-scraper/lib/index.js:225:102)
    at tryCatcher (/Users/ehsan/.config/yarn/global/node_modules/Bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/ehsan/.config/yarn/global/node_modules/Bluebird/js/release/promise.js:209:30)
    at Promise (/Users/ehsan/.config/yarn/global/node_modules/tiktok-scraper/lib/index.js:225:44)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by itsmrTech** [comment]
@el-lsan  Hey did you find out how to solve this?

**Comment by el-lsan** [comment]
@itsmrTech Unfortunately no!

**Comment by drawrowfly** [comment]
It seems that they've made few changes, host and added _signature value to the requests

I will update repo shortly

**Comment by shubs** [comment]
same issue

**Comment by drawrowfly** [comment]
Pushed an update that fixed the issue.

Cheers
