### ISSUE TITLE
Cannot find module Bluebird

### ISSUE THREAD

**Issue by dfinlay2** [drawrowfly/tiktok-scraper#3]
When runnning with nodejs v10.18.1 and installed with Yarn or npm, I receive this error when trying $tiktok-scraper --help

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'Bluebird'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/me/.config/yarn/global/node_modules/tiktok-scraper/lib/index.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/me/.config/yarn/global/node_modules/tiktok-scraper/lib/instance.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/me/.config/yarn/global/node_modules/tiktok-scraper/bin/cli.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by drawrowfly** [comment]
Pushed new update, it should work

**Comment by mhuzaifaa** [comment]
Getting new error now.
When runnning with nodejs v8.17.0 and installed with npm,

/tiktok-scraper$ tiktok-scraper --help
/usr/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:5:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by drawrowfly** [comment]
tiktok-scraper requires Node.js v8.6.0+ to run.

**Comment by mhuzaifaa** [comment]
Thanks for your reply @drawrowfly I am using v8.17.0  which is higher version of what your app required but it's not working. Really appreciate if its worked.

**Comment by drawrowfly** [comment]
@mhuzaifaa  I've recently added signature generation that is done with the help of jsdom, and it requires to have minimum Node v. 10 +

**Comment by mhuzaifaa** [comment]
Its Working on Node v.10 Thanks @drawrowfly 

Great work!
