### ISSUE TITLE
Getting error on Windows

### ISSUE THREAD

**Issue by VincentVinTin** [drawrowfly/tiktok-scraper#35]
**Script**
const TikTokScraper = require('tiktok-scraper');
 
(async () => {
    try {
        const posts = await TikTokScraper.hashtag('singing', { number: 100 });
        console.log(posts);
    } catch (error) {
        console.log(error);
    }
})();

**Version:**
"tiktok-scraper": "^1.0.13"

**Error:**
...\node_modules\jsdom\lib\jsdom\living\helpers\dates-and-times.js:235
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\node_modules\jsdom\lib\jsdom\living\helpers\form-controls.js:18:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\node_modules\jsdom\lib\jsdom\living\helpers\focusing.js:5:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by youngvo** [comment]
@VincentVinTin somehow, you have to modify to add `error ` in Catch statement. Then the code should be working fine
```
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch(error) {
    return false;
  }
}
```

**Comment by drawrowfly** [comment]
@VincentVinTin node version?

**Comment by VincentVinTin** [comment]
> @VincentVinTin somehow, you have to modify to add `error ` in Catch statement. Then the code should be working fine
> 
> ```
> function isDate(obj) {
>   try {
>     Date.prototype.valueOf.call(obj);
>     return true;
>   } catch(error) {
>     return false;
>   }
> }
> ```

Thanks! It's fixed.
