### ISSUE TITLE
Error when downloading by hastags and store

### ISSUE THREAD

**Issue by Blast06** [drawrowfly/tiktok-scraper#36]
**this is the error:**

the command: 
` tiktok-scraper hashtag tiktokchefs -d -n 30 -store`

```
C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\lib\helpers\multipleBar.js:42
        this.stream.clearLine();
                    ^

TypeError: this.stream.clearLine is not a function
    at Multibar.terminate (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\lib\help                                                                                           ers\multipleBar.js:42:21)
    at ProgressBar.bar.terminate (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\l                                                                                           ib\helpers\multipleBar.js:33:22)
    at ProgressBar.tick (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\node_modul                                                                                           es\progress\lib\node-progress.js:103:10)
    at Multibar.tick (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\lib\helpers\m                                                                                           ultipleBar.js:56:17)
    at ProgressBar.bar.tick (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\lib\he                                                                                           lpers\multipleBar.js:28:18)
    at Request.r.get.on.on.chunk (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper\l                                                                                           ib\index.js:117:34)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\_my_user\AppData\Roaming\npm\node_modules\tiktok-scraper                                                                                           \node_modules\request\request.js:1073:12)
    at IncomingMessage.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:122:22)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

It downloads a file(a corrupt zip file) with one video in it, but just only that.

**Comment by Blast06** [comment]
by the way, the video, i can't open it, since the zip is corrupted

**Comment by drawrowfly** [comment]
Duplicate #15 

Update fixing the current issue will be pushed shortly
