### ISSUE TITLE
Error: Cannot find module '../build'. Trying to install TikTok-Scraper from a git folder.

### ISSUE THREAD

**Issue by ProgrammingLife** [drawrowfly/tiktok-scraper#489]
**Describe the bug**
Trying to install tiktok-scraper from a local downloaded git folder but it doesn't run after successfull installation. That's how I do this:

**To Reproduce**
```
$ tiktok-scraper --version    
zsh: command not found: tiktok-scraper

$ cd /home/denis/programs/
$ git clone https://github.com/drawrowfly/tiktok-scraper.git
$ cd tiktok-scraper
$ sudo npm i -g .

$ cd /
$ tiktok-scraper --version  
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '../build'
Require stack:
- /home/denis/programs/tiktok-scraper/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/denis/programs/tiktok-scraper/bin/cli.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/denis/programs/tiktok-scraper/bin/cli.js' ]
}
```

If I install it from NPM seems all works fine except not the latest version of the module :)
```
$ cd /home/denis/programs/
$ sudo npm r -g .
$ tiktok-scraper --version    
zsh: command not found: tiktok-scraper

$ cd /
$ sudo npm i tiktok-scraper
$ tiktok-scraper --version                                                        
1.4.17
```
1.4.17 <- this version can't download videos without TT watermark (```tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 --hd -d -w```). It still stays on video.

**Env:**
- OS: Linux Mint 19.1
- NodeJs Version (node -v): v13.14.0
- Scraper Version: doesn't work (trying to install the latest version from github)
- CLI or Module: CLI
- Used method: sudo npm r -g .

**Screenshots**
n/a

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/103

**Comment by ProgrammingLife** [comment]
It doesn't work like that. I did:
```
$ npm root -g
/usr/lib/node_modules

$ sudo mv node_modules node_modules.bak0

$ apt remove nodejs
$ apt install nodejs

$ tiktok-scraper
zsh: command not found: tiktok-scraper

$ cd /home/denis/programs/
$ git clone https://github.com/drawrowfly/tiktok-scraper.git
$ cd tiktok-scraper
$ sudo npm i -g .

$ cd /
$ tiktok-scraper --version  
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '../build'
Require stack:
- /home/denis/programs/tiktok-scraper/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/denis/programs/tiktok-scraper/bin/cli.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/denis/programs/tiktok-scraper/bin/cli.js' ]
}
```

**Comment by ProgrammingLife** [comment]
@drawrowfly, I see this line: https://github.com/drawrowfly/tiktok-scraper/blob/9d89a0fc9b35d45c288be33d49122033eff620d4/bin/cli.js#L9
```
const TikTokScraper = require('../build');
```
but where this module is? I can't find it anywhere.

**Comment by ProgrammingLife** [comment]
Got it. I just needed to compile it with ```tsc```. Now it works.
