### ISSUE TITLE
Cant extrack on heroku but work on local

### ISSUE THREAD

**Issue by QUERY-GANI** [drawrowfly/tiktok-scraper#512]
**Describe the bug**
`2021-04-03T16:01:09.390719+00:00 app[web.1]: Error: Can't extract video metadata: https://www.tiktok.com/@tiktok/video/6807491984882765062
2021-04-03T16:01:09.390732+00:00 app[web.1]: at TikTokScraper.getVideoMetadata (/app/node_modules/tiktok-scraper/build/core/TikTok.js:797:15)
2021-04-03T16:01:09.390733+00:00 app[web.1]: at async TikTokScraper.getVideoMeta (/app/node_modules/tiktok-scraper/build/core/TikTok.js:808:25)
2021-04-03T16:01:09.390733+00:00 app[web.1]: at async Object.exports.getVideoMeta (/app/node_modules/tiktok-scraper/build/entry.js:169:20)
2021-04-03T16:01:09.390734+00:00 app[web.1]: at async module.exports (/app/server/fitures/tiktok_download.js:15:23)
2021-04-03T16:01:09.390735+00:00 app[web.1]: at async /app/server/routes/downloader.js:64:16`

**Code :**
[tiktok_download.js](https://github.com/QUERY-GANI/shinoa-api/blob/main/server/fitures/tiktok_download.js) 
[downloader.js](https://github.com/QUERY-GANI/shinoa-api/blob/main/server/routes/downloader.js)

**To Reproduce**
- Used Heroku
- NodeJs Version v14.16.0
- Scraper Version 1.4.18
- Module
- Used getVideoMeta
- Used options : noWaterMark, headers, sessionList
- URL to video : https://www.tiktok.com/@tiktok/video/6807491984882765062

**Screenshots**
**description : Got error when use heroku**
![image](https://user-images.githubusercontent.com/73988956/113484362-1d447200-94d2-11eb-8b0a-523f0f969e71.png)

**description : try on localhost**
![image](https://user-images.githubusercontent.com/73988956/113484607-677a2300-94d3-11eb-87db-670c61575ceb.png)

**Comment by drawrowfly** [comment]
not scraper related problem. use proxies and always, Always(5 more times) check the latest version!
