### ISSUE TITLE
Can't extract video metadata for every video

### ISSUE THREAD

**Issue by hypo-thesis** [drawrowfly/tiktok-scraper#530]
```
0|server  | Error: Can't extract video metadata: https://www.tiktok.com/@francesca.capaldi/video/6923315966944267526?lang=en&is_copy_url=1&is_from_webapp=v1
0|server  |     at TikTokScraper.getVideoMetadata (/www/wwwroot/ytdl.uk.to/api/node_modules/tiktok-scraper/build/core/TikTok.js:789:15)
0|server  |     at async TikTokScraper.getVideoMeta (/www/wwwroot/ytdl.uk.to/api/node_modules/tiktok-scraper/build/core/TikTok.js:800:25)
0|server  |     at async Object.exports.getVideoMeta (/www/wwwroot/ytdl.uk.to/api/node_modules/tiktok-scraper/build/entry.js:169:20)
0|server  |     at async default (file:///www/wwwroot/ytdl.uk.to/api/tiktok.js:29:23
```

my code at error :    `const videoMeta = await TikTokScraper.getVideoMeta(url, { headers }).catch(error => {`

This error occurs on every video. It was working a week ago without any issues.

**Comment by hypo-thesis** [comment]
@drawrowfly Closing the issue without any explanation is not in keeping with the spirit of programing.
