### ISSUE TITLE
Docker image not building

### ISSUE THREAD

**Issue by o7n** [drawrowfly/tiktok-scraper#540]
**Describe the bug**
Docker image is not building

**To Reproduce**
- Ubuntu 20.04.1, Intel CPU

```
apt install docker.io
git clone https://github.com/drawrowfly/tiktok-scraper
cd tiktok-scraper/
docker build . -t tiktok-scraper
```

**Output**

```
Sending build context to Docker daemon   34.8MB
Step 1/18 : FROM alpine:latest AS tiktok_scraper.build
 ---> 28f6e2705743
Step 2/18 : WORKDIR /usr/app
 ---> Using cache
 ---> 5e21d0337afa
Step 3/18 : RUN apk update && apk add --update nodejs nodejs-npm python3
 ---> Using cache
 ---> 73d3c52bc640
Step 4/18 : COPY package*.json tsconfig.json .prettierrc.js bin ./
 ---> 885fd8c2c530
Step 5/18 : COPY ./src ./src
 ---> 0419dbb87178
Step 6/18 : RUN npm i
 ---> Running in 4e5cd29fb834

> canvas@2.7.0 install /usr/app/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-linux-musl-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.7.0 and node@14.16.0 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
/bin/sh: pkg-config: not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-70-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/app/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /usr/app/node_modules/canvas
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/app/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-70-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/app/node_modules/canvas
node-pre-gyp ERR! node -v v14.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/app/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-03T13_37_34_830Z-debug.log
The command '/bin/sh -c npm i' returned a non-zero code: 1

```

**Comment by asportnoy** [comment]
Try following the manual instructions from https://github.com/Automattic/node-canvas/wiki#installation-guides

**Comment by hanshansenrl** [comment]
might be related, but i cant use scraper anymore either in pipedream (Request must be smaller than 69905067 bytes for the PublishLayerVersion operation) in my require('tiktok-scraper'); line

**Comment by drawrowfly** [comment]
I will check it out shortly, need to finish update

**Comment by rezzonic** [comment]
> I will check it out shortly, need to finish update

Hi, I ran into the same issue and fixed it -- see my pull request.

**Comment by apastel** [comment]
> Hi, I ran into the same issue and fixed it -- see my pull request.

Can confirm these changes in your PR worked for me.

**Comment by alexmerm** [comment]
Can also confirm that PR #558 works

**Comment by drawrowfly** [comment]
@1.4.33
