### ISSUE TITLE
TypeError: Cannot read property 'tick' of undefined

### ISSUE THREAD

**Issue by yonas** [drawrowfly/tiktok-scraper#549]
**Describe the bug**
After download several videos of a TikTok user, I get this error:

```
Downloading (WITH WM) 175193233503834112 [======================        ] 71%
Downloading (WITH WM) 174343599130742784 [==============================] 100%
Downloading (WITH WM) 174747754961932288 [=====                         ] 16%Empty response! You can try again with a proxy! Can't download video: 173304513829863424
/usr/lib/node_modules/tiktok-scraper/build/core/Downloader.js:83
                        barIndex.tick(chunk.length, { id: item.id });
                                 ^

TypeError: Cannot read property 'tick' of undefined
    at Request.<anonymous> (/usr/lib/node_modules/tiktok-scraper/build/core/Downloader.js:83:34)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/tiktok-scraper/node_modules/request/request.js:1073:12)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.Readable.read (_stream_readable.js:507:10)
    at flow (_stream_readable.js:1007:34)
    at resume_ (_stream_readable.js:988:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

- Used OS
Ubuntu 20.04.2 LTS

- NodeJs Version (node -v)
v12.22.1

- Scraper Version (tiktok-scraper --version)
1.4.23

- CLI or Module
CLI

- Used method
user

- Used options
kayceerice -d -n 0 -s --historypath ~/tiktok/kayceerice --filepath ~/tiktok/kayceerice

- Do you run the scraper through Proxy, VPN, VPS?
No.

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, the profile is public.

- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@kayceerice

**Screenshots**

![Screenshot from 2021-05-11 19-00-44](https://user-images.githubusercontent.com/110130/117894928-5e773100-b28b-11eb-8ec9-7b5be7803a0e.png)

**Comment by yonas** [comment]
Pull request #550 was merged. Closing this issue.
