### ISSUE TITLE
Not Implemented Error

### ISSUE THREAD

**Issue by ItsABlackScreen** [drawrowfly/tiktok-scraper#596]
**Describe the bug**

When Bulk scraping it throws the following error for every user.
<pre>
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at e (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:4094)
    at f (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:397)
    at e (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:1117)
    at e (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:1246)
    at e (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:1842)
    at f (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:397)
    at e (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:966)
    at f (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:397)
    at Object.e [as sign] (eval at <anonymous> (eval at <anonymous> (eval at sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:14:12))), <anonymous>:1:1117)
    at Object.sign (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/helpers/Signature.js:15:34)
    at TikTokScraper.getValidHeaders (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/core/TikTok.js:540:43)
    at TikTokScraper.submitScrapingRequest (private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/core/TikTok.js:334:28)
    at private/.nvm/versions/node/v15.4.0/lib/node_modules/tiktok-scraper/build/core/TikTok.js:301:49 undefined
</pre>
substituted private for home directory.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS - Fedora 33
- NodeJs Version (node -v) - v15.4.0
- Scraper Version (tiktok-scraper --version) - 1.4.32
- CLI or Module - Cli
- Used options
- tiktok-scraper from-file location 1 -d -n 20 -s --filepath location --historypath location  --session sid_tt=id
- Do you run the scraper through Proxy, VPN, VPS? - VPN
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Profile public and visible in browser.
- Preferably provide URL to the profile,hashtag,video and etc page - For all users.

**Comment by asportnoy** [comment]
Try [these steps](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Prebuilt). If that doesn't work, [try these](https://github.com/Automattic/node-canvas/wiki#installation-guides).

**Comment by ItsABlackScreen** [comment]
> Try [these steps](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Prebuilt). If that doesn't work, [try these](https://github.com/Automattic/node-canvas/wiki#installation-guides).

That seems to have done the trick. I leave it up for andrew to close the issue, as maybe the requirements need to be updated. Thanks for the help.

**Comment by asportnoy** [comment]
Andrew said it's an issue with the latest version and he'll get it fixed. He accidentally removed the node-canvas library from the module.

**Comment by ItsABlackScreen** [comment]
In that case i will be closing the issue.
