### ISSUE TITLE
Installing doesn't work

### ISSUE THREAD

**Issue by atmos-o** [drawrowfly/tiktok-scraper#617]
Installed NodeJS, then npm, and did `npm i -g tiktok-scraper`. This is what I got:
```
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/tiktok-scraper -> /usr/local/lib/node_modules/tiktok-scraper/bin/cli.js

> canvas@2.8.0 install /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build'
gyp ERR! System Linux 5.8.0-59-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/usr/local/lib/node_modules/tiktok-scraper/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.8.0-59-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/tiktok-scraper/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-09T14_07_49_047Z-debug.log
sv@server:~/tts$ ^C
sv@server:~/tts$ su root
Password:
su: Authentication failure
sv@server:~/tts$ su -i root
su: invalid option -- 'i'
Try 'su --help' for more information.
sv@server:~/tts$ su -i root^C
sv@server:~/tts$ su -i rootsudo -^C
sv@server:~/tts$ sudo -i
root@server:~# npm i -g tiktok-scraper
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/local/bin/tiktok-scraper -> /usr/local/lib/node_modules/tiktok-scraper/bin/cli.js

> canvas@2.8.0 install /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build'
gyp ERR! System Linux 5.8.0-59-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/usr/local/lib/node_modules/tiktok-scraper/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.8.0-59-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/tiktok-scraper/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-09T14_15_52_357Z-debug.log
```

**Comment by boscacci** [comment]
I am getting a similar error. I had a previous version of tiktok-scraper installed and it has stopped working; I attempted to update to the latest version via npm without success so far.

A sample from the error msg:
![image](https://user-images.githubusercontent.com/12357390/125672660-efbd10e9-3940-472a-b4c3-9a4049db592b.png)

**Comment by boscacci** [comment]
Tried installing with YARN. Full error message attached:
`yarn global add tiktok-scraper

yarn global v1.22.10
[1/4] 🔍  Resolving packages...
warning tiktok-scraper > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning tiktok-scraper > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning tiktok-scraper > request > har-validator@5.1.5: this library is no longer supported
warning tiktok-scraper > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/rob/.config/yarn/global/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/rob/.config/yarn/global/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@16.5.0 | darwin | arm64
node-pre-gyp info check checked for "/Users/rob/.config/yarn/global/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.5.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.5.0 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.5.0 | darwin | arm64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
(node:82653) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/Cellar/node/16.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/.config/yarn/global/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/Cellar/node/16.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/Library/Caches/node-gyp/16.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rob/Library/Caches/node-gyp/16.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/Cellar/node/16.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rob/Library/Caches/node-gyp/16.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rob/.config/yarn/global/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/Cellar/node/16.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command "/opt/homebrew/Cellar/node/16.5.0/bin/node" "/opt/homebrew/Cellar/node/16.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93" "--python=/usr/bin/python"
gyp ERR! cwd /Users/rob/.config/yarn/global/node_modules/canvas
gyp ERR! node -v v16.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rob/.config/yarn/global/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/16.5.0/bin/node" "/Users/rob/.config/yarn/global/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rob/.config/yarn/global/node_modules/canvas
node-pre-gyp ERR! node -v v16.5.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rob/.config/yarn/global/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=/usr/bin/python' (1)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.`

**Comment by boscacci** [comment]
This issue was resolved (on arm64/m1/apple silicone) after I ran `brew install pkg-config cairo pango libpng jpeg giflib librsvg`

**Comment by atmos-o** [comment]
I'm currently on Ubuntu (Same issue occured on Windows)

**Comment by alievk** [comment]
This is a known `npm` issue with permissions. I configured it to use a custom directory for which I don't need a sudo and it worked out:
1. Manually change npm's default directory (or user an alternative option) to a path over which you have a full access https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
2. `npm i -g tiktok-scraper`
3. 🎉

**Comment by atmos-o** [comment]
@alievk Your solution worked for me on Ubuntu. But I see the "Manually change npm's default directory" step is not possible on Windows so some users may not be able to do this.

**Comment by xhackj** [comment]
I have the following error on my CentOS after installation.

[root@vultr ~]# tiktok-scraper --help
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/share/.config/yarn/global/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/canvas/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by UnixCro** [comment]
tiktok-scraper is the best tiktok downloader

**Comment by billsix123** [comment]
How to solve it on windows ?

**Comment by billsix123** [comment]
> windows下如何解决？

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code EBUSY
npm ERR! syscall rmdir
npm ERR! path C:\Users\huzuoxi\AppData\Roaming\npm\node_modules\tiktok-scraper\node_modules\canvas
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\huzuoxi\AppData\Roaming\npm\node_modules\tiktok-scraper\node_modules\canvas'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huzuoxi\AppData\Roaming\npm-cache\_logs\2021-07-29T03_34_54_234Z-debug.log

**Comment by tablatronix** [comment]
@boscacci dep install solution worked for me on new mac mini m1. Thanks!

**Comment by Incher25** [comment]
I have same installing issue on Ubuntu 20.04, so I installed tiktok-scraper locally in my project dir. But after that when I try to run `tiktok-scraper --help` I get this error:

```
$ tiktok-scraper --help
/home/my_project_dir/node_modules/canvas/index.js:1
const Canvas = mrequire('./lib/canvas')
               ^

ReferenceError: mrequire is not defined
    at Object.<anonymous> (/home/my_project_dir/node_modules/canvas/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/my_project_dir/node_modules/jsdom/lib/jsdom/utils.js:160:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/my_project_dir/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
I've googled this error but there are no results with "mrequire" being mentioned.

**Comment by StarshineLight** [comment]
Same using the Termux app on android.

**Comment by amberallergy** [comment]
Hi!
This one seems to work can try it out, they offer free token at the first.
Also work on different social media platforms.
Here is the website https://www.influencerhunters.com/docs.html

**Comment by Developerusman** [comment]
Hello everyone 

I've solved this issue by just running "npm i tiktok-scraper" in terminal instead of "npm i -g tiktok-scraper" 

i think  this error is show because you have no tiktok-scraper dependencies in package.json the reason of this error is when we run with -g it will install the package globally but not in package.json so when we run without -g then it will just install into your project means package.json 
 
its works for me hopefully it will works for you as well 

please give tumbs up if it works for you 

Thanks :)

**Comment by gpietrafesavieitez** [comment]
In my case (Raspberry Pi) there is no longer precompiled package canva@2.8.0 for ARM and it is necessary to build it from source code. I solved it just simply installing some necessary packages from this solution:

https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems

Hope someone will find this helpful :)

**Comment by sagar-spreadd** [comment]
This error is due to missing dependency packages 

-> install using brew
brew install pkg-config cairo pango libpng jpeg giflib librsvg

-> npm i tiktok-scraper

**Comment by rzkyh4ack** [comment]
> Installed NodeJS, then npm, and did `sudo npm i -g tiktok-scraper`. This is what I got:
> 
> ```
> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> /usr/local/bin/tiktok-scraper -> /usr/local/lib/node_modules/tiktok-scraper/bin/cli.js
> 
> > canvas@2.8.0 install /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build'
> gyp ERR! System Linux 5.8.0-59-generic
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> gyp ERR! node -v v10.19.0
> gyp ERR! node-gyp -v v6.1.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/usr/local/lib/node_modules/tiktok-scraper/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> node-pre-gyp ERR! System Linux 5.8.0-59-generic
> node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/tiktok-scraper/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> node-pre-gyp ERR! node -v v10.19.0
> node-pre-gyp ERR! node-pre-gyp -v v1.0.5
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the canvas@2.8.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-07-09T14_07_49_047Z-debug.log
> sv@server:~/tts$ ^C
> sv@server:~/tts$ su root
> Password:
> su: Authentication failure
> sv@server:~/tts$ su -i root
> su: invalid option -- 'i'
> Try 'su --help' for more information.
> sv@server:~/tts$ su -i root^C
> sv@server:~/tts$ su -i rootsudo -^C
> sv@server:~/tts$ sudo -i
> root@server:~# npm i -g tiktok-scraper
> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> /usr/local/bin/tiktok-scraper -> /usr/local/lib/node_modules/tiktok-scraper/bin/cli.js
> 
> > canvas@2.8.0 install /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build'
> gyp ERR! System Linux 5.8.0-59-generic
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
> gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> gyp ERR! node -v v10.19.0
> gyp ERR! node-gyp -v v6.1.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/usr/local/lib/node_modules/tiktok-scraper/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> node-pre-gyp ERR! System Linux 5.8.0-59-generic
> node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/tiktok-scraper/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas
> node-pre-gyp ERR! node -v v10.19.0
> node-pre-gyp ERR! node-pre-gyp -v v1.0.5
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the canvas@2.8.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-07-09T14_15_52_357Z-debug.log
> ```

first you need install node.js it work for me
