### ISSUE TITLE
Can't extract video metadata when deployed to Heroku or Digital Ocean

### ISSUE THREAD

**Issue by BrunoQuaresma** [drawrowfly/tiktok-scraper#655]
When I run `TikTokScraper.getVideoMeta` locally it works as expected. but when I deploy the app to Heroku I get the following error:
```
Error: Can't extract video metadata: https://www.tiktok.com/@tiktok/video/6807491984882765062 
  at TikTokScraper.getVideoMetadata (/app/node_modules/tiktok-scraper/build/core/TikTok.js:835:15)
  at async TikTokScraper.getVideoMeta (/app/node_modules/tiktok-scraper/build/core/TikTok.js:846:25)
  at async Object.exports.getVideoMeta (/app/node_modules/tiktok-scraper/build/entry.js:169:20)
  at async Object.downloadVideo (/app/utils.js:24:21)
  at async /app/index.js:19:5
```

I also tried to deploy on Digital Ocean and I'm receiving the same error:
```
Error: Can't extract video metadata: https://www.tiktok.com/@levimcclainmusic/video/6989286959621344517?is_copy_url=1
[tweetpik-extra-api] [2021-08-18 14:52:33]     at TikTokScraper.getVideoMetadata (/workspace/node_modules/tiktok-scraper/build/core/TikTok.js:835:15)
[tweetpik-extra-api] [2021-08-18 14:52:33]     at async TikTokScraper.getVideoMeta (/workspace/node_modules/tiktok-scraper/build/core/TikTok.js:846:25)
[tweetpik-extra-api] [2021-08-18 14:52:33]     at async Object.exports.getVideoMeta (/workspace/node_modules/tiktok-scraper/build/entry.js:169:20)
[tweetpik-extra-api] [2021-08-18 14:52:33]     at async Object.downloadVideo (/workspace/utils.js:24:21)
[tweetpik-extra-api] [2021-08-18 14:52:33]     at async /workspace/index.js:19:5
```

**Comment by drawrowfly** [comment]
use proxy
