### ISSUE TITLE
Can't extract video metadata 

### ISSUE THREAD

**Issue by vanities** [drawrowfly/tiktok-scraper#724]
**Describe the bug**
Getting
`Can't extract video metadata: {my url}` from share urls and regular urls

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: macOS
- NodeJs Version (node -v): v15.14.0
- Scraper Version (tiktok-scraper --version): 1.4.36
- CLI or Module: cli and module
- Used method: cli with `tiktok-scraper video {my ur}`
- Used options: just videos
- Do you run the scraper through Proxy, VPN, VPS? yes
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by vanities** [comment]
getting this: 
```
RequestError: Error: ESOCKETTIMEDOUT
    at new RequestError (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request/request.js:185:22)
    at Request.emit (node:events:369:20)    at ClientRequest.<anonymous> (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request/request.js:819:16)
    at Object.onceWrapper (node:events:475:28)
    at ClientRequest.emit (node:events:369:20)
    at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
    at Object.onceWrapper (node:events:475:28)
    at TLSSocket.emit (node:events:381:22)
    at TLSSocket.Socket._onTimeout (node:net:481:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  cause: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request/request.js:816:19)
      at Object.onceWrapper (node:events:475:28)
      at ClientRequest.emit (node:events:369:20)
      at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
      at Object.onceWrapper (node:events:475:28)
      at TLSSocket.emit (node:events:381:22)
      at TLSSocket.Socket._onTimeout (node:net:481:8)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  error: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/Users/vanities/git/work/funfunfun/tiktok-scraper/node_modules/request/request.js:816:19)
      at Object.onceWrapper (node:events:475:28)
      at ClientRequest.emit (node:events:369:20)
      at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
      at Object.onceWrapper (node:events:475:28)
      at TLSSocket.emit (node:events:381:22)
      at TLSSocket.Socket._onTimeout (node:net:481:8)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  options: {
    jar: RequestJar { _jar: [CookieJar] },
    uri: '{my url}',
    method: 'GET',
    headers: {
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4156.149 Safari/537.36',
      referer: 'https://www.tiktok.com/'
    },
    json: true,
    resolveWithFullResponse: true,
    followAllRedirects: false,
    simple: true,
    timeout: 10000,
    callback: [Function: RP$callback],
    transform: undefined,
    transform2xxOnly: false
  },
  response: undefined
}

on https://github.com/drawrowfly/tiktok-scraper/blob/5224f5cdfc3842a99b77b382249b960d2c87791c/src/core/TikTok.ts#L371
```

**Comment by vanities** [comment]
getting this: 
```
RequestError: Error: ESOCKETTIMEDOUT
    at new RequestError (/Users/vanities/git/tiktok-scraper/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/vanities/git/tiktok-scraper/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/vanities/git/tiktok-scraper/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/vanities/git/tiktok-scraper/node_modules/request/request.js:185:22)
    at Request.emit (node:events:369:20)    at ClientRequest.<anonymous> (/Users/vanities/git/tiktok-scraper/node_modules/request/request.js:819:16)
    at Object.onceWrapper (node:events:475:28)
    at ClientRequest.emit (node:events:369:20)
    at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
    at Object.onceWrapper (node:events:475:28)
    at TLSSocket.emit (node:events:381:22)
    at TLSSocket.Socket._onTimeout (node:net:481:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  cause: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/Users/vanities/git/tiktok-scraper/node_modules/request/request.js:816:19)
      at Object.onceWrapper (node:events:475:28)
      at ClientRequest.emit (node:events:369:20)
      at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
      at Object.onceWrapper (node:events:475:28)
      at TLSSocket.emit (node:events:381:22)
      at TLSSocket.Socket._onTimeout (node:net:481:8)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  error: Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/Users/vanities/git/tiktok-scraper/node_modules/request/request.js:816:19)
      at Object.onceWrapper (node:events:475:28)
      at ClientRequest.emit (node:events:369:20)
      at TLSSocket.emitRequestTimeout (node:_http_client:790:9)
      at Object.onceWrapper (node:events:475:28)
      at TLSSocket.emit (node:events:381:22)
      at TLSSocket.Socket._onTimeout (node:net:481:8)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ESOCKETTIMEDOUT',
    connect: false
  },
  options: {
    jar: RequestJar { _jar: [CookieJar] },
    uri: '{my url}',
    method: 'GET',
    headers: {
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4156.149 Safari/537.36',
      referer: 'https://www.tiktok.com/'
    },
    json: true,
    resolveWithFullResponse: true,
    followAllRedirects: false,
    simple: true,
    timeout: 10000,
    callback: [Function: RP$callback],
    transform: undefined,
    transform2xxOnly: false
  },
  response: undefined
}
```

on https://github.com/drawrowfly/tiktok-scraper/blob/5224f5cdfc3842a99b77b382249b960d2c87791c/src/core/TikTok.ts#L371

**Comment by vanities** [comment]
@drawrowfly Sorry, why did you close this?

**Comment by drawrowfly** [comment]
before creating new issues check the one that are already created
