### ISSUE TITLE
Tiktok has changed response for username scraping. 

### ISSUE THREAD

**Issue by bojanmilinkovic** [drawrowfly/tiktok-scraper#725]
In the function
public async getUserProfileInfo(): Promise<UserMetadata>
Where there comes to splitting by <script> tag, there is an error because that script tag is changed and the rest of the function can not parse expected json

**Comment by Alexo88** [comment]
is not working for me

**Comment by TheFacelessOne** [comment]
Error: Can't extract user metadata from the html page. Make sure that user does exist and try to use proxy
    at TikTokScraper.getUserProfileInfo (node_modules\tiktok-scraper\build\core\TikTok.js:713:15)
    at async Object.exports.getUserProfileInfo (node_modules\tiktok-scraper\build\entry.js:138:20)

**Comment by junio-AC** [comment]
Same probem here using user function. Scraper seems to start but then there is no output

**Comment by bfeldman89** [comment]
> Same probem here using user function. Scraper seems to start but then there is no output

same

**Comment by foftycent** [comment]
same.. starts but nothing downloads.. any alternatives anyone found ? cant seem to find anything

**Comment by skmachine** [comment]
https://rapidapi.com/neotank/api/tiktok-bulletproof take a look at this scraping solution, it offers limited set of endpoints but is pretty stable.

**Comment by pvita** [comment]
> same.. starts but nothing downloads.. any alternatives anyone found ? cant seem to find anything

same problem.
Any solution?

**Comment by Oxicode** [comment]
> I've been using this https://www.npmjs.com/package/got-scraping
> 
> with this little function
> 
> I'm only using it for the same tiktok account everytime though and only to check the follower count 🤷
> 
> ```
> async function TikTokUpdate() {
>     console.log('Tiktok update started')
>     const Tok = await gotScraping({ url: 'TIKTOK USER URL' });
> 
>     const start = Tok.body.indexOf('followers-count');
>     const end = Tok.body.indexOf('<', start);
>     const tikTokF = Tok.body.slice(start + 17, end);
>     console.log('Tiktok followers = ' + tikTokF);
> 
>     return parseInt(tikTokF);
> }
> ```

thank you very much

**Comment by bakharew** [comment]
> > same.. starts but nothing downloads.. any alternatives anyone found ? cant seem to find anything
> 
> same problem. Any solution?

+1
