### ISSUE TITLE
Very nooby linux issue

### ISSUE THREAD

**Issue by EduardJipa** [drawrowfly/tiktok-scraper#88]
Honestly I'm very new to linux, have always been a windows developer until I thought I'd try this package; I've installed Node.JS & its requirements as well as this project (I believe), yet whenever I try any syntax it throws up the same error;
```

/usr/local/lib/node_modules/tiktok-scraper/bin/cli.js:8
const { tmpdir } = require('os');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```
This is after simply calling tiktok-scraper --help, same result occurs via sudo or any other command.
Any help would be greatly appreciated;
Cheers

**Comment by drawrowfly** [comment]
Follow the issue template, until then issues closed

PS

> Installation
> tiktok-scraper requires Node.js v10+ to run.
